version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library
      - ENVIRONMENT=development
      - LOG_LEVEL=info
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  test:
    build: .
    command: pytest --maxfail=1 --disable-warnings -q
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/library_test
      - ENVIRONMENT=testing
      - TESTING=1
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge